server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_URL}/${DB_SCHEMA}?useUnicode=true&characterEncoding=utf-8"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    url: jdbc:mysql://mysql.group25.svc.cluster.local:3306/container_demo?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: password

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.deerowl.model

logging:
  level:
    org.springframework.web: ERROR
    cn.deerowl: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  server:
    port: 9090
  endpoint:
    shutdown:
      enabled: false
    beans:
      enabled: false
